name: flutter_application_diamond_shop_final
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  persian_number_utility: ^1.1.4
  shared_preferences: ^2.2.3
  connectivity_plus: ^4.0.1
  shamsi_date: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: YB
      fonts:
        - asset: assets/fonts/YekanBakh_Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakh_Fat.ttf
          weight : 900
        - asset: assets/fonts/YekanBakh_Regular.ttf
          weight: 400

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500
        - asset: assets/fonts/ShabnamBold.ttf
          weight : 700


